version: "3.9"

services:
  web:
    build: .
    container_name: flask-redis-app-web
    ports:
      - "5001:5001"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: flask-redis-app-redis
    ports:
      - "6379:6379"
